### ISSUE TITLE
Swipe to Navigate Back in iOS not working

### ISSUE THREAD

**Issue by nihalreddy33** [kalismeras61/flutter_page_transition#19]
I am unable to swipe back when using the PageTransition. Is there any way to enable it?

**Comment by kwent** [comment]
Yes,

It's cause this library is completely overriding `buildTransitions` implemented by `CupertinoPageRoute` and so `_CupertinoBackGestureDetector` is not implemented at all.

I managed to modify the library internally with those diffs to make it work left to right (since right to left is the default).

**This is `NOT RECOMMENDED` for production use and might break at any time.**

Differences are: https://github.com/flutter/flutter/compare/master...kwent:cupertino_page_route_left_to_right.

Include https://gist.github.com/kwent/d2763bc2ca894bfbb2191350d006c6d8 in your project and call

```dart
import './CupertinoPageRoute.dart' as right
```

```dart
Navigator.push(
    context,
    right.CupertinoPageRoute(
        context: context,
        builder: (context) {
          return Center(child:Text('Hello world'));
        }));
```

**Comment by kalismeras61** [comment]
This is Cupertino issue. Closing for now.
